### ISSUE TITLE
Error in data loader with test data

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/mosviz#107]
When reading data in, MOSViz spits out error messages about non-existent files. This happens even though the files are present. Like:

[Errno 2] No such file or directory: 'spec1D/spec1d.1153.151.12004808.fits'
[Errno 2] No such file or directory: 'spec2D/slit.1153.151R.fits.gz'
[Errno 2] No such file or directory: 'cutouts/12004808.acs.v_6ac_.fits'
[Errno 2] No such file or directory: 'spec1D/spec1d.1153.151.12004808.fits'
[Errno 2] No such file or directory: 'spec2D/slit.1153.151R.fits.gz'
[Errno 2] No such file or directory: 'cutouts/12004808.acs.v_6ac_.fits'
....
.....

The error can be seen in both test data sets listed in https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=DATB&title=MosViz

With the Keck/DEIMOS data set, even when the error messages are present, the files are properly read and MOSViz behaves fine from there on. With the simulated JWST data, MOSViz raises exceptions of type ValueError("No table found"). Empty plots result.

**Comment by javerbukh** [comment]
I'm getting a very similar error. @ibusko are you on windows?

**Comment by ibusko** [comment]
@javerbukh no, I am on Mac OSX.

**Comment by ibusko** [comment]
The errors I reported above show up in my personal dev installation from sources. When I install mosviz as per instructions on the Installation page, using a pristine conda installation, I get errors like the one below. This is from the same DEIMOS data set that works on my dev installation.

(base) kamino:/Users/busko $ glue
[Errno 2] No such file or directory: 'spec1D/spec1d.1153.151.12004808.fits'
[Errno 2] No such file or directory: 'spec2D/slit.1153.151R.fits.gz'
[Errno 2] No such file or directory: 'cutouts/12004808.acs.v_6ac_.fits'
WARNING: hdu= was not specified but multiple tables are present, reading in first available table (hdu=1) [astropy.io.fits.connect]
WARNING:astropy:hdu= was not specified but multiple tables are present, reading in first available table (hdu=1)
Traceback (most recent call last):
  File "/Users/busko/Projects/miniconda3_mosviz/lib/python3.6/site-packages/mosviz/viewers/mos_viewer.py", line 142, in <lambda>
    lambda ind: self.load_selection(self.catalog[ind]))
  File "/Users/busko/Projects/miniconda3_mosviz/lib/python3.6/site-packages/mosviz/viewers/mos_viewer.py", line 481, in load_selection
    spec1d_data = loader_spectrum1d(row[colname_spectrum1d])
  File "/Users/busko/Projects/miniconda3_mosviz/lib/python3.6/site-packages/mosviz/loaders/jwst_loaders.py", line 24, in nirspec_spectrum1d_reader
    data.add_component(tab['WAVELENGTH'], "Wavelength")
  File "/Users/busko/Projects/miniconda3_mosviz/lib/python3.6/site-packages/astropy/table/table.py", line 1222, in __getitem__
    return self.columns[item]
  File "/Users/busko/Projects/miniconda3_mosviz/lib/python3.6/site-packages/astropy/table/table.py", line 106, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'WAVELENGTH'

**Comment by ibusko** [comment]
I'm not entirely sure, but I suspect part of the problem has to do with paths.

I also found other 2 problems with the jwst test data set.

1 - the 2D images have extensions named SCI and CON, while the mosviz reader expect DATA and VAR.

2 - the files in the spec1D/ directory are supposed to store tables with the extracted 1D spectra. They store images instead:

Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.io import fits
>>> fits.open("/astro/3/jwst_da_sprint_testdata/mostools/workshop_examples/jwst/spec1D/Final_spectrum_MOS_1_015_107_CLEAR-PRISM_MOS_PRISM-observation-2-c0e0_000.fits")
[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x81cf5ae10>, <astropy.io.fits.hdu.image.ImageHDU object at 0x81cf92f28>, <astropy.io.fits.hdu.image.ImageHDU object at 0x81cf9b940>, <astropy.io.fits.hdu.image.ImageHDU object at 0x81cf9be80>]
>>> 
>>> from astropy.table import Table
>>> Table.read("/astro/3/jwst_da_sprint_testdata/mostools/workshop_examples/jwst/spec1D/Final_spectrum_MOS_1_015_107_CLEAR-PRISM_MOS_PRISM-observation-2-c0e0_000.fits")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/busko/Projects/miniconda3_mosviz/lib/python3.6/site-packages/astropy/table/table.py", line 2531, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/Users/busko/Projects/miniconda3_mosviz/lib/python3.6/site-packages/astropy/io/registry.py", line 517, in read
    data = reader(*args, **kwargs)
  File "/Users/busko/Projects/miniconda3_mosviz/lib/python3.6/site-packages/astropy/io/fits/connect.py", line 199, in read_table_fits
    astropy_native=astropy_native)
  File "/Users/busko/Projects/miniconda3_mosviz/lib/python3.6/site-packages/astropy/io/fits/connect.py", line 186, in read_table_fits
    raise ValueError("No table found")
ValueError: No table found
>>> 
>>>

**Comment by ibusko** [comment]
The errors are present under version 0.1.1. They do not show up in the dev version (installed from source master in repo).

Closing.
