### ISSUE TITLE
Move test data to artifactory

### ISSUE THREAD

**Issue by eteq** [spacetelescope/mosviz#114]
I just noticed there's ~9MB of files in the ``mosviz/tests/data/`` directories that look to be test files. In general it's dangerous to put such large files in git repos, and anyway it's problematic to bloat the source distribution unnecessarily this way.

So what about instead hosting the testing files on artificatory? I'm not an expert in how to do this, but this is something STScI is already paying for to do *exactly* this sort of thing (store large test data externally).

**Comment by javerbukh** [comment]
Contact Matt Rendina about hosting data

**Comment by eteq** [comment]
Note that this is a bit overtaken by #137.  Artifactory is a good place for *large* datasets and the like, but it's probably not great for.

It's still an open question whether some of the *future* (especially, e.g., JWST) datasets should be in artifactory for other more end-to-end tests, though.  This requires coordination with SCSB as the keepers of the pipeline, so probably not worth stressing about immediately.

**Comment by nmearl** [comment]
I've also spoken with Matt and he's willing to set up a repository for us whenever we're ready (I'll probably send around some information on gaining access).

**Comment by nmearl** [comment]
Based on @eteq it seems we should invest in either embracing git LFS, or the astropy setup-another-data-only-repo. Since we're invested in the astropy template eco-system already, it seems the latter would be preferred.

**Comment by hcferguson** [comment]
I still wonder whether [dvc](https://dvc.org/features) is worthy of investigation or experimentation.

**Comment by brechmos-stsci** [comment]
I think you are looking for https://zenodo.org/record/1421377/files/deimos.zip...

**Comment by javerbukh** [comment]
Yes, thank you!

**Comment by javerbukh** [comment]
Covered by #157
