### ISSUE TITLE
Displaying Multiple Slits

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/mosviz#116]
Right now MOSViz displays a single slit and its corrosponding 2D spectrum by aligning the y axes as follows:
<img width="2230" alt="screen shot 2018-09-10 at 9 35 30 am" src="https://user-images.githubusercontent.com/10345916/45300645-ec982980-b4dc-11e8-9ece-a81689729358.png">

Should MOSViz have the ability to display multiple slits at once? If so how should the cutout slit to 2d image alignment work?

**Comment by eteq** [comment]
After some discussion in a sprint tag-up, we concluded this is not necessary - we are choosing to "define it away" in that one slit is one row in the table, and if it's two disjoint segments that can be encoded in the "region".

So conceptually there's only one "slit" per table row.
