### ISSUE TITLE
Video demo for release 0.2

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/mosviz#134]
It would be good to have a short (2-3 min) video demonstrating the basic use of MOSViz. Things to demonstrate might be:

- [ ] Read in a JWST NIRSpec data set
- [ ] Create a set of NIRCam postage stamps
- [ ] Select a few spectra from the table
- [ ] Lock the axes in both the spectral and spatial direction
- [ ] Zoom and pan in both directions
- [ ] Zoom in on a spectral feature, pop into specviz and fit it

Optional if there is time:

- [ ] Demonstrate blinking between level 2 and level 3 data products

**Comment by mfixstsci** [comment]
@javerbukh In my mind, we would do something similar to the SpecViz demo:

https://specviz.readthedocs.io/en/latest/#demo

Looks like it covers the basics of the UI. Assuming we can open SpecViz in MOSViz, we can do some of the line fitting shown in the demo. Let me know what you think of this idea!

**Comment by nmearl** [comment]
Note that model fitting is not fully implemented in the new specviz.

**Comment by mfixstsci** [comment]
Hey @brechmos-stsci, sounds good to me. We need to add the audio over the video we shot from a few weeks ago. The feedback from the team about what we had in hand + the specviz embedded in mosviz functionality with audio would be sufficient as a demo for the release.

**Comment by brechmos-stsci** [comment]
Another ticket will be opened for an updated video once specviz is embedded.
