### ISSUE TITLE
Cutout won't display with JWST data set

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/mosviz#141]
The cutout display for the JWST data set is not working. It shows a blank image. 

The error was present before the level 2 support code was merged. I eventually figured that somehow it has to do with the slit drawing mechanism. If I comment out line 753 in mos_viewer.py  (image_widget.set_slit_limits()), the image displays, but then the slit itself won't display. The axis labels differ in each case, suggesting that it could be a WCS-related problem. 

The error is not present when using the DEIMOS data set.

**Comment by robelgeda** [comment]
The cutouts for the JWST data do not have correct WCS information. The images are displaying but are out of view.
