### ISSUE TITLE
NIRSpec generation

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/mosviz#147]
I've been trying to track down whether the pipeline would be JWST producing the NIRSpec table, relieving MOSViz of the need to do so. At the moment, the answer is no, but it would be possible to request this. Before deciding whether or not to do that, I thought perhaps we should discuss it here. We need to address these issues regardless of where the table generation is implemented. 

- We don't yet know how to specify non-rectangular slits, so we need to address this regardless, which means we need to know how the pipeline is planning to convey this information in the output files. 
- We should include information on the background extraction in the table, since you might want to filter in making plots or  selecting sources to inspect
- APT knows whether the source is supposed to be a point source or extended. We should try to get this info into the table as well, since that might be a tag people want to use for quality assessment.
- The current implementation in table_generator.py mixes GUI code and the basic operation of generating the table into one module, and it looks like it's only accessible through the GUI. I think it would be better to separate the code for generating the table into its own module and provide an example in the docs of running it from the python prompt, with some discussion in the docs to suggest that people can customize this for their own unique data sets.

**Comment by hcferguson** [comment]
The _s2d.fits file SCI extension has the following info on the slit and the target position in the slit:

```
S_REGION= 'POLYGON ICRS  156.249361896 -45.678780096 156.249438170 &'           
CONTINUE  '-45.678780096 156.249438170 -45.678708136 156.249361896 &'           
CONTINUE  '-45.678708136&'                                                      
CONTINUE  '' / spatial extent of the observation                                

SLTSTRT1=                 1958 / Starting pixel in x direction                  
SLTSIZE1=                   91 / Number of pixels in x direction                
SLTSTRT2=                 1781 / Starting pixel in y direction                  
SLTSIZE2=                   18 / Number of pixels in y direction                
SRCXPOS =   -0.671999990940094 / Source position in slit (x-axis)               
SRCYPOS =   -0.805899977684021 / Source position in slit (y-axis)               
SHUTSTA = 'x       '           / All (open and close) shutters in a slit        
```

(Not absolutely certain I'm looking at the latest-generation output file in the above.)

MOSViz in its current state expects slit-width and slit-height, which can be inferred from SLTSIZE, but that requires finding the arcsec per pixel conversion somewhere. It would be nice to be able to populate the MOSViz table without having to go to a separate CRDS reference file to get such information. Looks like the S_REGION should do the trick. So when we get to implementing regions in MOSViz this is probably the way to go. 

It's unclear to me what the units for `SRCXPOS` and `SRCYPOS` are, and whether they will be relevant for non-rectangular slits. Needs some guidance from @jdavies-st or @philhodge.

**Comment by hcferguson** [comment]
Not instantly finding documentation on how `S_REGION` is defined. In the first two examples I've looked at, it seems like walking from the first to second corner is along the dispersion direction, because this is shorter than the distance between the second & third corner. Is this correct, and is it always the case?

If so, until we figure out what to do with regard to JWST data models in MOSViz, we can read the FITS headers, make these SkyCoord objects and, compute what MOSViz needs as follows:
```
width_arcsec = corner0.separation(corner1).to('arcsecond').value
length_arcsec = corner1.separation(corner2).to('arcsecond').value
position_angle = corner1.position_angle(corner2).to('degree').value
```
Does this make sense @philhodge or @jdavies-st or @nden?

Tagging @SaOgaz as well...and @robelgeda since he might have already thought this through for our current NIRSpec loader?

**Comment by robelgeda** [comment]
@hcferguson I was hoping for something like this! This would help further automate the table generation.

**Comment by nden** [comment]
The S_REGION keyword is intended to store the spatial footprint of an imaging observation using the VO standard STCS representation. It's recomputed in various steps in the pipeline. Normally the corners of the image in pixels are transferred to sky using the WCS. Nirspec is a bit special because the result of applying the WCS transforms to the corners of the slitlet is always NaNs, so we use other methods. The order of the vertices listed in the S_REGION string should move counter-clockwise around the perimeter for a sky orientation that has North up and East to the left (RA increasing to the left). I hope that's what we have now.

**Comment by philhodge** [comment]
The keyword database gives this definition of S_REGION:  "spatial extent of the observation, footprint".  Looking at assign_wcs/util.py, however, it looks to me as if this keyword gives the right ascension and declination at the corners of a quadrilateral that contains `model.meta.wcs.bounding_box`.  The slit projected onto the sky can of course be tilted with respect to RA and Dec, but the limits of S_REGION are the minimum and maximum RA and Dec, not the coordinates of the corners of the slit projected onto the sky.  With regard to judging the dispersion and cross-dispersion directions from the slit dimensions, I don't think that's reliable.  The S1600A1 fixed slit (I realize you said MOS) is square.  Also, with the MSA you probably could open multiple adjacent shutters in the cross-dispersion direction, making an aperture that is wider in the dispersion direction.

According to the keyword database, SRCXPOS and SRCYPOS are the estimate position of the source within a NIRSpec MSA shutter along the X- and Y-axis directions (dispersion and cross dispersion).  The keyword database also specifies that the source positions run from 0x0 at the top left corner of a shutter, as seen projected onto the sky, to 1x1 at the lower right corner of a shutter.  So the unit must be the shutter width and height, i.e. different physical sizes for SRCXPOS and SRCYPOS.

**Comment by nden** [comment]
`SRCXPOS` and `SRCYPOS` are measured relative to the center of the slitlet, so perhaps that's not very useful for mosviz. In case you need them I can dig out the complete info on the frame they are in .

**Comment by SaOgaz** [comment]
When I was chatting with @hbushouse about this, we we're looking at the pixelscale CDELT keywords in the s2d headers as a way to get the pixel to arcsecond conversion.  But I'm not super familiar with this stuff, so maybe that's not the right way to go about it?

**Comment by SaOgaz** [comment]
Forgot to say, that additionally Howard and I looked at the SLITSIZE1 and SLITSIZE2 keywords to get the dimensions of the slit.

**Comment by hbushouse** [comment]
SLITSIZEn do NOT give the size of the actual entrance slit. They give the size of the cutout region used to extract each 2-D cutout around each spectral trace from the original 2048x2048 MOS image. So SLITSIZE1, for example, which is in the dispersion direction, can be very large (10's or 100's of pixels), in order to cover the entire spectral trace end-to-end. This is WAY bigger than the actual entrance slit.

**Comment by hcferguson** [comment]
From James Muzerolle via email:

Unfortunately, I don't think those specific values are output anywhere.  The sky coordinates of the corners of each slit, or the center, can be calculated on the fly using the instrument model transforms, which are accessible from the data model in the *_cal.fits output.  The relevant quantities could be derived from that, all of which would only require a few lines of code.  That might be too cumbersome to include in MOSViz, though, in which case, we could try to file a ticket to have the pipeline write the info directly to the header corresponding to the SCI extension of each slit.

**Comment by hcferguson** [comment]
@SaOgaz Given James Muzerolle's comment and the thread above, my suggestion for right now is to use S_REGION for now (as done in the notebook I sent you) as if it has the information we need, since that information isn't in the headers right now.

**Comment by hcferguson** [comment]
Attempts to translate the current NIRSpec pipeline output into the old expected format by @hcferguson and @SaOgaz continue to fail. The most recent error log is attached. My feeling is that it is not worth pursuing this, but should instead concentrate on building an *interim* loader that will read the `_x1d.fits` and `_s2d.fits files` directly and generate the table on the fly. It will be *interim* in the sense that it will take the slit information from `S_REGION` as if it is accurate. We may need to change this in a later release if it turns out that data are recorded in some other data structure.

I'm thinking that it might not be hard to conquer the loader using a combination of @drdavella's NIRSpec loader for SpecUtils and the notebook that Sara & Harry worked on. 

Error log:
[mosvis_log_6dec.txt](https://github.com/spacetelescope/mosviz/files/2654898/mosvis_log_6dec.txt)

**Comment by SaOgaz** [comment]
@hcferguson, @nmearl tried to load the files with his new mosviz, but ran into the same WCS error.   I'm not sure what the source of this error is, do you know why it's happening, how we can fix it?

**Comment by nden** [comment]
@SaOgaz If the error you get is the one in the log above, it means the value of CUNIT3 is not FITS compliant. Try setting it to "um" instead of "micron".

**Comment by SaOgaz** [comment]
New error:
"Encounted an error during WCS parsing. Discarding world coordinates! 
ERROR 13 in wcssub() at line 815 of file cextern/wcslib/C/wcs.c:
Non-separable subimage coordinate system."

**Comment by astrofrog** [comment]
https://github.com/spacetelescope/mosviz/issues/220 is a related issue regarding the issues with _x2d files.
