### ISSUE TITLE
Loader Selection Bug 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/mosviz#156]
There is a bug in the MOSViz loader selection ui where the slit parameter combo boxes appear unpopulated. To trigger this bug, first drag the data into glue and select MOSViz Viewer. The loader selection should pop up and look normal. If you close that dialog out without pressing ok and reopen the dataset using MOSViz, you will see that one of the attributes in the paramaters section has an empty combo box. If you repeat this, the next combo box loses its listings. 

Example (after opening the loader 3 times):
<img width="480" alt="screen shot 2019-01-14 at 2 39 29 pm" src="https://user-images.githubusercontent.com/10345916/51136409-6c772d00-180a-11e9-8b12-f13d4c5e60de.png">
 

@astrofrog

**Comment by astrofrog** [comment]
Ok I'll look into it!
