### ISSUE TITLE
What JWST pipeline data can we use for unit tests

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/mosviz#157]
We should add unit tests for the following files if we can get clearance from the NIRSpec team:

NIRSpec MSA (lvl 2 data)
f170lp-g235m_mos_observation-6-c0e0_001_dn_nrs1_mod_cal_ref.fits   
f170lp-g235m_mos_observation-6-c0e0_001_dn_nrs1_mod_s2d_ref.fits   
f170lp-g235m_mos_observation-6-c0e0_001_dn_nrs1_mod_x1d_ref.fits

**Comment by javerbukh** [comment]
Test with real files using Box (needs loader that can actually use these files first #168 ).

**Comment by javerbukh** [comment]
Make sure this works with level 2 and level 3 data

**Comment by SaOgaz** [comment]
If this happens, #184 and #200 will be un-blocked.

**Comment by SaOgaz** [comment]
We got clearance on the files listed from Nora (NIRSpec team), but I need to compare these files to the ones Robel has.  If they match, we can use this file set for a level 2 unit test.  Official level 3 unit test data is not currently available from the team.

**Comment by SaOgaz** [comment]
Level 3 test data posted on box, etc.  Level 2 data may be different in the future, so putting this one off.
