### ISSUE TITLE
Cutout tool is not responsible for bad input WCS

### ISSUE THREAD

**Issue by pllim** [spacetelescope/mosviz#16]
Just want to point out that in comparing results from #15, where the same region is extracted using `Cutout2D` (no rotation) or `reproject` (with rotation), when the input image has "bad" WCS, cutout does not always get the correct region.

Left is using `Cutout2D`, right is using `reproject` with -5.3 degrees rotation for object ID `CANDELS_GDS_F160W_J033248.05-274737.4`:
<img width="241" alt="untitled2" src="https://cloud.githubusercontent.com/assets/2090236/16477054/672f0a14-3e5c-11e6-918d-3d5ec9f8c261.png">

The input image is [hlsp_candels_hst_wfc3_gsd01_f125w_v0.5_drz.fits](https://archive.stsci.edu/pub/hlsp/candels/goods-s/gsd01/v0.5/hlsp_candels_hst_wfc3_gsd01_f125w_v0.5_drz.fits), which gives the following warning in Astropy WCS:

```python
>>> from astropy.io import fits
>>> from astropy.wcs import WCS
>>> hdr = fits.getheader(imagefile)
>>> wcs = WCS(hdr)
INFO: 
                Inconsistent SIP distortion information is present in header:
                SIP coefficients were detected, but CTYPE is missing "-SIP" suffix,
                therefore the coordinates calculated here might be incorrect.

                If image is already distortion-corrected (eg, drizzled) then
                distortion components should not apply. For such distortion-corrected
                images, please use ``wcs_pix2world`` or ``wcs_world2pix`` instead.

                If image is not yet distortion-corrected (eg, not yet drizzled), then
                please inspect the header and make appropriate changes before rerunning.
                 [astropy.wcs.wcs]
```

I believe this has been extensively discussed in astropy/astropy#4761 and beyond the control of the cutout tool. If you don't give a good WCS, just don't expect a proper cutout.

c/c @larrybradley , @astrofrog , @hcferguson

**Comment by hcferguson** [comment]
Agreed.

**Comment by larrybradley** [comment]
+100
