### ISSUE TITLE
Long-term plan for NIRSpec Aperture information and overlays (Discussion topic)

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/mosviz#171]
This issue is for discussion. Open other issues for implementation once we have a plan. 

## User Story

As a JWST observer I need to know what patch of sky is contributing to my observation in order to properly interpret the results.

## Elaboration

MOSVis should be able to project the following information onto a NIRCam (or other) image:

1. The MSA aperture used for a single observation for a single slit (i.e. a level 2 product)
2. An exposure map of all the MSA apertures that were combined into a level 3 product
3. Ability to turn on and off planes of this exposure map corresponding to individual dithers (or some similar way to visualize the different dithers overlayed on a single image)
4. For level 2 and level 3:
   1. The MSA aperture (e.g. displayed as an outline or alpha channel on the NIRCam image)
   2. The pipeline extraction aperture used for this source
   3. The background apertures used for this source
   4. Similar ability at level 3 to turn on and off individual dithers or view just one dither at a time

## Implementation discussion

Most of this information is not in the current _x1d files, and the above user story goes well beyond what we have built so far in any case. For the ultimate tool:

- We should not assume that the slit is a rectangle
- We need some way to specify potentially irregular aperture(s) on the sky
- We need a position angle to rotate the image so that the dispersion is horizontal 
- We have to design the UI to show the various flavors of aperture 

### How to convey this information to the users?

There are various ways one could imagine storing the aperture information. 

1. As an Astropy [region](https://astropy-regions.readthedocs.io/en/latest/) specification.
2. As a segmentation image of the full MSA projection on the sky. This is very compressible.
3. As a bunch of small postage stamps, one per MSA source. 
    1. These could be bitmaps, one bit per dither. 
    2. Or they could be exposure maps. 

Option 1 is maybe the most in line with thinking of this as metadata. And it's likely to take the least amount of storage. But the Astropy regions package is still in early development. It doesn't seem to have a way to specify multiple disjoint regions, which may be required for the background regions. There is also no obvious way in the region specification to indicate which is the dispersion and cross-dispersion direction.  

Option 2 is familiar to SExtractor users. For the MSA, the pixels would be the MSA apertures, and the WCS would provide the information for projecting this onto the sky. An advantage of this format is that it would be easy in  ginga to overlay this on a NIRCam image or blink it against a NIRCam image. The WCS is distorted enough that it might not be easy to do this in ds9. Because this is the MSA projection on the sky, the dispersion direction is along rows and cross-dispersion is along columns. 

Option 3 Seems is closest in concept to the postage stamp images in MOSViz. Each postage stamp would have its own WCS, and would likely be small enough that one could ignore distortion for projecting this on top of another image postage stamp. It seems most useful to have this as exposure maps. In the case of level 3 products, there would be one exposure map per dither position. These would each have to have their own WCS, so can't easily be packaged as a data cube. This option has the advantage that it is quite straightforward to handle disjoint background apertures. The dispersion would be along rows of these postage stamps and cross-dispersion along columns.

#### Packaging 

Option 1 is could perhaps be implemented by adding metadata to the _x1d (and _x2d files, for completeness). 

Option 2 might be best as a completely new data product. 

Option 3 could be packaged either way, but might be simplest for developers and users as a completely separate data product.

### Displaying the aperture overlay

The postage stamp image (from NIRCam or some other camera) is rotated so the horizontal direction runs along the dispersion and the vertical direction is in the cross-dispersion direction, aligned with the _x2d 2D spectrum. For options 2 or 3, overlaying is fairly straightforward because both have their own WCS. One creates an alpha plane for each dither, with different colors for the different kinds of apertures. And with options to turn on and off each aperture. 

Overlaying with regions would require that we work out how get the orientation of dispersion and cross-dispersion. But then the regions package is designed with overlays in mind, so might handle the rest of the geometric transformations. 

So...please indicate your preferences in the comments.
Option 1, 2 or 3 ...

### Opinions?

What's best for users @kassin @eteq? 

Data model implications? Pipeline concerns? @perrygreenfield @nden @hbushouse 

Others feel free to vote & comment (just don't want to tag everyone individually).

**Comment by hcferguson** [comment]
Actually, I think I'm wrong about the the statement for segmaps that in ginga "it would be easy to overlay on an NIRCam image." Ginga doesn't resample the images, it just shifts them (right @plim?). So if you view a large enough field, the distortions of the NIRCam image and the MSA segmap will be different and they will give misleading offsets. This removes what I thought might be the major advantage of having the slit locations be in a segmap. I lean strongly toward option 3, as a new data product.

**Comment by hcferguson** [comment]
After discussions with @kassin and James Muzerolle, it seems like option 1 has significant advantages over for two aspects of the overall problem:

- viewing background apertures; in principle these could be spread around the detector
- viewing apertures projected on a NIRCam image. The regions package already supports this for quite a few different visualization tools.

**Comment by hcferguson** [comment]
@drdavella, @nden, @perrygreenfield Do you have any thoughts on the best way to capture the region information in the JWST data models and the best way to serialize it to files? Some musings below...

The JWST `MultiSlitModel` currently has a special member called `slits` that carries information associated with a single source. For keeping all the info together, it may be useful to extend this to include the aperture geometry information, but it could get rather long and involved. For clarity, I'm going to call these collections of data and metadata `sources` rather than `slits` in the discussion below.  

## Level 2 
Level 2 is relatively straightforward:

- There is one MSA region per source (most astronomers would call this collection of open MSA apertures "the slit"; it is a collection of open micro-shutters). The detector itself allows arbitrary geometries of open microshutters. I believe the MPT only supports rectangular, contiguous collections of open micro-shutters. So we could assume these are rectangular, but to be safe for the future it is probably better to allow arbitrary polygons. I don't see an immediate need to allow multiple disconnected micro-shutters for sources. (Although....come to think of it, coming down to the wire for cycle-1 proposals on one proposal team we were tempted to try a Hadamard transform arrangement that would be non-contiguous).
- There is a separate "extraction aperture" per source which may not have the same footprint on the sky as the MSA open apertures, so needs a separate region specification.
- In the basic use case, there are two apertures on either side of the source MSA aperture that are used for background. But it is also possible for users to group apertures spread over the field into a master background. According to James the team has been assuming that users would use the same background apertures for all the sources for this use case, but he admitted that users might want to tailor this. So it's probably safest for us to assume that each source can have an arbitrary number of background regions.

## Level 3
Level 3 is much more complicated. The detector images are rectified and combined before doing the 1D extraction. There will certainly be shifts in the MSA projection on the sky for the different dithers in an observation, and there could even be rotations.  What this means is that for the level 3 products there is not just one collection of MSA open shutters to project on the sky, but multiple collections that will partially overlap. So for each of the aperture types discussed at level 2, we now have N times as many, where N is the number of dithers. Each of these is still associated with a single source (i.e. `slit` in the `MultiSlitModel`). 

## Storage in the data model

Storing this in the `MultiSlitModel` data model doesn't seem like a big deal. Just need a data structure that is a region, or list of regions (e.g. master background regions at level 2) or dictionary of regions (e.g. level 3 extraction apertures projected back to correct RA & Dec for each dither position), or dictionary of list of regions (background apertures projected back onto the sky for each dither position). 

We also need metadata somewhere that specifies the position angle of the dispersion axis, so that we can rotate the NIRCam image to the right orientation when projecting these apertures.

## Storage in FITS and/or ASDF

Serializing these data in FITS seems like a nightmare. Putting them in the ASDF extension is probably straightforward. So we would need to decide if it is sufficient to have the information there and not in the FITS metadata.

**Comment by perrygreenfield** [comment]
regarding different extraction apertures from group apertures:

How would this be determined? From the proposal, or some other algorithm in the pipeline? Not that it affects the serialization and data model but it may relate to what may exist as the variants that have to be dealt with.

regarding position angle of the dispersion axis:

I’m unclear about this part. Presumably that only makes sense if there is one orientation on the sky for the slits. Otherwise the dispersion direction on the sky will be in multiple directions. Are you only talking about the limited case where there is only one orientation?

regarding nightmares:

I think you’ve answered the question. Unless you mean selecting out a few simple things for FITS headers.

**Comment by perrygreenfield** [comment]
But region information can be captured in two different frames. For the level 2 stuff, it can be described in the slit plane, while using the wcs to convert it to world coordinates when combining data. For slits it would seem natural to use a polygon representation for the spatial coordinates and use the wcs model to map that from one frame to another. So each combined spectrum could be associated with a set of slit footprints (e.g., a dict keyed by the corresponding exposure or equivalent). All these are easy to map into an ASDF extension. There are a number of decisions to make, such as do you want to store with the footprint the exposure time or just reference the exposure and obtain the exposure time from a common dictionary? Things like that. The footprint polygon with the WCS effectively contain the information on the orientation, but that could be extracted as a quantity to be saved specially along with the footprint data.

**Comment by hcferguson** [comment]
@perrygreenfield you are probably right that users will want to know the positions of the apertures in both frames. Or maybe all three frames: detector pixels, MSA pixels, and sky coordinates. I'm not sure that WCSs are a great way to capture this information though. Right now I don't think regions have their own WCSs; they are just supposed to be able to use a WCS if given one to translate from pixels to sky and vice versa. For that reason, I'd be inclined to store the regions in sky coordinates and then let users use the WCSs of any images they have to translate those to pixels. The other way around is messier because the _x1d and _x2d files don't currently have the relevant WCSs of the NIRSpec detector or the MSA. 

Regarding orientations....yes in principle it can project in multiple directions if the spectrum
is coming from separate exposures taken at different roll angles. I think we'd want a way to display that, so I think carrying around the relevant roll angles even if there are several is worthwhile.

**Comment by perrygreenfield** [comment]
@hcferguson It all depends on how you want to associate the information. If the footprints are associated with the spectrum, the question is whether one wants to know what original data they correspond to. If one does want that link (that data doesn't have to be in the same file) then the footprint can retrieve the wcs corresponding to it. Likewise, roll angle is something that can be obtained from the WCS, but it is overkill if roll angle is all you care about (that can be stored just as an angle). But the main question for a combined 1d spectrum is what links are desired to the data that contributed to it. It seems useful to me to have that spectrum be able to trace back to the original data. Another question is whether these 1d spectra will be in their own file or in the same file as many others derived from the same collection of data.

**Comment by hcferguson** [comment]
@perrygreenfield Currently the 1D spectra are collected together in a single _x1d file. Likewise for the 2D spectra, in a single _x2d file. I assume there are metadata to link back to the original files, but scanning an example _x1d header, it's not obvious. It probably gives enough information to *construct* a file name from the observation identifiers, but there's not an actual  filename of the _cal file. I do that the headers have the name of an MSA metafile, which I haven't looked at. That will presumably provide the info on which MSA shutters are open for which source.

**Comment by hbushouse** [comment]
The collecting of multiple instances of data only occurs in level-2b and level-2c products. Once level-3 products are created, there will be a separate product for each source/slit that only contains a single (combined) data instance. For example, if you have 3 nodded MOS exposures each containing 5 sources/slits, you will get 3 level-2b _cal and _x1d products, each of which will contain the data for the 5 sources/slits in separate extensions. At the beginning of calspec3 processing, the _cal data get rearranged to create 5 source-based products, each of which contains the data from the 3 exposures for a given source/slit. These are saved as source-based level-2c products, for convenience of off-line analysis or reprocessing by users (they're interested in working on the data for one source at a time and not having that data spread around in multiple files). 

The data from the 3 exposure instances for each source are then combined into a level-3 2-D resampled (s2d) product, from which a final 1-D spectrum is extracted and saved in a level-3 x1d product. So you'll end up with 5 source-based s2d and x1d products, each of which contain a single image or spectrum for a single source.

**Comment by hcferguson** [comment]
Wow. Is this a recent change? I could have sworn the _x1d files we have been using recently were supposed to be representative of level 3 products, not just level 2.  @SaOgaz @jdavies-st ?

**Comment by hbushouse** [comment]
Not at all a recent change in plans, but potentially only recently available in the actual processing and hence the supply of examples (although I believe we built some examples by hand before the processing was available). For example, if you look in:

/grp/jwst/ssb/test_build7.1/examples_for_dms/level3/calwebb_spec3/nirspec_msa/

you'll find a bunch of example files that consist of 3 exposures of 3 sources/slits. The exposure-based products - jw95065006001_02101_0000[123]_nrs1_<suffix>.fits - all contain 3 instances of data (one for each source/slit). 

The level-2c source-based cal products - jw95065-a3001_s0000[123]_nirspec_f100lp-g140m_cal/crf.fits - also contain 3 data instances, but now those are the data from the 3 exposures for a given source (source id's in the file names are "s00001", "s00002", and "s00003").

Then the level-3 source-based s2d and x1d products - jw95065-a3001_s0000[123]_nirspec_f100lp-g140m_s2d/x1d.fits - each contain a single data instance, which is the result of combining the data from the 3 exposures for each source.

I'm guessing the examples you were given are probably from level-2b processing, as opposed to level-3.

By the way, the examples sitting in that directory are quite old already (from 2017), so processing details may have changed enough since then to make their header contents a little different, etc. We could try rerunning them through the latest software to generate fresh versions.

**Comment by hcferguson** [comment]
@hbushouse Having fresh versions is pretty important, since we are revising the loader for MOSViz. Is there a more formal writeup somewhere of the packaging you outlined in your previous comment?

It's unfortunate that your example files have the same number of sources as exposures. Very confusing! 

When you say for level 2b that the "exposure-based products ...all contain 3 instances of data", would these files then have 5 extensions if there were 5 slits? And there would still be 3 files, one per exposure? Correct?

And then at level-2c and level-3 I understand that for 5 slits, there would be now be 5 files, one for each slit, named for the source-ID. (Which is incidentally, what we originally thought, so our current loader and helper-tool should actually work for those).

**Comment by robelgeda** [comment]
I talked to @jdavies-st and he gave me the latest level 3 data possible. In one file you may have multiple slits and is extension based. The good news is that each source has a unique `SOURCEID` that we can use to link `x1d` and `s2d` counterparts. Also, the headers contain all the information we need to construct a MOSViz table with the exception of the slit width and height. @hcferguson @kassin

**Comment by hbushouse** [comment]
> In one file you may have multiple slits and is extension based.

That should never be the case with level-3 data products. Because the data from different slits correspond to different sources, and level-3 products are supposed to only contain the data for a single source, you should only have data from a single slit. I'd be interested in seeing these latest level 3 data. If the statement above is correct, then the level-3 pipeline is in error.

**Comment by hbushouse** [comment]
https://jira.stsci.edu/browse/JP-542 has been filed to document and fix this error in the `calwebb_spec3` pipeline.

**Comment by jdavies-st** [comment]
After discussing this with @hbushouse, it looks like the products that are currently being created by the `Spec3Pipeline` are not correct.  The different sources should be split out into different files.  Currently these are all collated together at the end and written to one file.  So this needs to be fixed, as mentioned above.

**Comment by drdavella** [comment]
Just had a discussion with @jdavies-st and if I understood correctly, this should make the `mosviz` loader **much** simpler.

Since each `*_s2d` and `*_x1d` each will contain only a single spectrum, it just becomes a matter of correlating the two files and reading a spectrum from each one. Since the filenames are expected to match up to the `_s2d`/`_x1d` component, this should be trivial. I might be missing part of the picture here, but it seems like this could potentially eliminate the need for table files altogether.

**Comment by hcferguson** [comment]
The table just makes the correspondence between them so you don't have to search the files each time or rely on a file naming convention. But since that's what we already implemented, the loader for level 3 ought to basically work as is (although the slit geometry info is still lacking of course).

**Comment by kassin** [comment]
@drdavella Keep in mind that non-JWST data will still require the table.

**Comment by hcferguson** [comment]
From James Muzerolle:

Hi Susan, Harry,

I've been looking into the data model for the NIRSpec level 2b products (the unrectified spectra, *cal.fits).  Some good news - it is possible to access the instrument model transforms in order to calculate sky positions for apertures.  The attached jupyter notebook shows an example using one of the NIRSpec simulated MOS exposures; you should be able to run this since the fits file is on central store (warning - the step that opens the data model will take a fairly long time to complete since there are a total of 72 slitlets in this case).  What I did here was to calculate the sky coordinates for the four corners of each open shutter containing a source, along with the sky position of the source itself given the planned pointing from MPT.  The last cell plots the last shutter in the list of slitlets, along with its source. The four corners are connected with straight lines, which does not take into account the distortion, though that should be a minor effect; if necessary, one could just calculate the transform of more points in the slit plane to make that more accurate.  I think this is at least part of what you were aiming for?  I'm still looking into how to plot the entire slitlet rather than just the target shutter, it's not quite as straightforward as this.  Let me know what you think!

Best,
James

--- 
I can't attach the notebook, but here's the key steps:
```
from jwst.assign_wcs import nirspec
from jwst import datamodels

infile_2b='/grp/jwst/wit4/nirspec/Muzerolle/Sim_products/F170LP-G235M_MOS_observation-6-c0e0_001_DN_NRS1_mod_updatedHDR_cal.fits'

mos = datamodels.open(infile_2b)

x = np.array([-0.5,-0.5,0.5,0.5])
y = np.array([-0.5,0.5,0.5,-0.5])
for slit in mos.slits:
#    print(vars(slit))
    name = slit.name
    srcx = -0.5-slit.source_xpos
    srcy = -0.5-slit.source_ypos
    print ("\nWorking with slit: ", name)
    print ("source ID: ", slit.source_id)
    print ("source slit position: ", slit.source_xpos,slit.source_ypos,srcx,srcy)
    wcsobj = slit.meta.wcs
    gwa2slit = wcsobj.get_transform('gwa','slit_frame')
    slit2sky = wcsobj.get_transform('slit_frame','world')
    skyx, skyy, _ = slit2sky(x,y,1.4*10**-6)
    srcskyx, srcskyy, _ = slit2sky(srcx,srcy,1.4*10**-6)

import matplotlib.pyplot as plt
plt.plot(np.append(skyx,skyx[0]),np.append(skyy,skyy[0]))
plt.plot(srcskyx,srcskyy,marker="*",markersize=20.)
plt.ylim(plt.ylim()[::-1])
plt.xlabel("RA (deg)")
plt.ylabel("DEC (deg)")
plt.show()
```

Output is in the screenshot attached. 

<img width="429" alt="screen shot 2019-02-21 at 3 58 00 pm" src="https://user-images.githubusercontent.com/2261329/53201290-93870280-35f1-11e9-916e-6d51ef7bd96e.png">
