### ISSUE TITLE
JWST Level 2 loader tests

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/mosviz#184]
Write tests for level 2 loader and viewer once we get shareable test data.

**Comment by SaOgaz** [comment]
I need to find out what we can make publicly available.

**Comment by SaOgaz** [comment]
@hcferguson, @robelgeda and I just discussed the details of doing the unit tests, and we've got a good idea for a couple unit tests for the sample level 3 data that Robel put together, but we don't feel a level 2 test with our current data would be worth it.  Are you okay with us removing this from the version 0.3 project?

**Comment by hcferguson** [comment]
@SaOgaz Is the reason that the level 2 data aren't representative? I actually thought we had level 2 data that were closer to the final expected product than level 3.

**Comment by robelgeda** [comment]
@hcferguson: I thought it might be better to hold off on the tests until we get #213 resolved. This is because we would expect to see some change in the file structure. We could run a simple test to see if level2 products load into MOSViz (i.e single column level2 spectrum) but further detailed tests might have to be rewritten in the future.

**Comment by hcferguson** [comment]
@SaOgaz sounds reasonable.

**Comment by SaOgaz** [comment]
Tagged the wrong issue to close on my PR.
