### ISSUE TITLE
MOSViz not being loaded as Glue module

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/mosviz#185]
[Recent updates](https://github.com/spacetelescope/mosviz/pull/179/files#diff-2eeaed663bd0d25b7e608891384b7298L117) to the setup.py file causes MOSViz to not appear in the list of viewer when opening glue. This is evident when you try to drag and drop a MOS table; mosviz is not in the list of viewers. You may have to do a fresh install of glue to notice this behavior since you probably already have mosviz added in past installs. 

cc @drdavella

**Comment by astrofrog** [comment]
It looks like the glue plugin entry point is missing from ``setup.cfg``
