### ISSUE TITLE
possible to make side panel widths adjustable?

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/mosviz#188]
From testing session with James Muzerolle:

James was working with a smaller screen, and mentioned it would be nice if he could make the sidebars smaller.  We saw the option to completely collapse them, but is it possible to make them more custom adjustable?

**Comment by robelgeda** [comment]
@astrofrog : We might want to add a hide sidebar button like we did for CubeViz?

**Comment by astrofrog** [comment]
The minimum width of the side bar is constrained by the widgets inside the sidebar, so below a certain size you can only hide or show the sidebar but not make it e.g. 50 pixels wide. The button @robelgeda is mentioning would be good for people who don't realize they can collapse the side bar but I don't think we can make the sidebar be completely flexible in terms of width.

Having said that, if you find an example where you think there is unnecessary space wasted in the sidebar, please send me screenshots and I can try and optimize it.
