### ISSUE TITLE
nomenclature in top 2d image drop-down unclear

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/mosviz#189]
From testing session with James Muzerolle:

One of the top drop downs has a few choices between level2, un-rectified, etc.  These are quite correct.  You can have both rectified and un-rectified for level 2 and level 3 JWST products.  So these options need to be re-tooled a bit.  Not sure what the right name for this drop down is, maybe @robelgeda can clarify and re-title this issue a bit better.

James' off the cuff name suggestions: "un-rectified 2D spectrum", "rectified 2D spectrum" etc.

**Comment by robelgeda** [comment]
This is a long term question. Turning this to a discussion and opening a new ticket for the v0.3 milestone.
