### ISSUE TITLE
Plot cutout with labels in arcsec?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/mosviz#19]
Comment from Susan, "The labels on the postage stamps should have the option of being in arcseconds, not just pixels (if possible)."

@larrybradley , @astrofrog -- Is there anything in Astropy that can already do this? I don't want to reinvent the wheel here.

**Comment by larrybradley** [comment]
I'm not exactly sure what you are asking, but if you know the pixel scale (arcsec/pix) then you can use Astropy units to easily go back and forth between pixels and arcsec.

**Comment by astrofrog** [comment]
@pllim - yes, there is now mostly a mechanism to do this - you could use WCSAxes coupled with the new ``SkyOffset`` frames. I can try and provide an example later.

An easier way to do this would be to use the ``proj_plane_pixel_scales`` function to convert from pixel to arcseconds as @larrybradley is suggesting, and then use the matplotlib ``extent`` option in imshow to tell it the range of 'world coordinates'.

I will add an example for both of these to the WCSAxes docs shortly.

**Comment by pllim** [comment]
@astrofrog , could you please link the relevant docs here, when they are available, to keep a record? Thanks!

**Comment by astrofrog** [comment]
@pllim - will do - ping me if I don't do it in a timely fashion!

**Comment by pllim** [comment]
@astrofrog , maybe I should write a bot to remind you! :wink:

**Comment by pllim** [comment]
Moved to spacetelescope/astroimtools#33
