### ISSUE TITLE
mosviz viewer inner window spawned too much to the left

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/mosviz#190]
From testing session with James Muzerolle:

When James finished opening his table, the inner mosviz viewer window spawned to far over to the left, so some of the content was cut off.  He was able to drag the window into a better position, but it seemed buggy that it didn't spawn with better placement.  This was on a mac machine.

**Comment by robelgeda** [comment]
Yeah, it was weird. We should try to get an old 13-inch laptop form ITSD and test our tools. It would serve as a bottleneck test.

**Comment by astrofrog** [comment]
@SaOgaz - are there any screenshots of the issue available?

**Comment by SaOgaz** [comment]
@astrofrog unfortunately not at the moment. We can try and re-create it at some point.
