### ISSUE TITLE
review and update mosviz documentation

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/mosviz#199]

**Comment by hcferguson** [comment]
Annotated the current documentation at https://hyp.is/go?url=https%3A%2F%2Fmosviz.readthedocs.io%2Fen%2Flatest%2Fapi.html

**Comment by SaOgaz** [comment]
We're going to go with a slimmed down version of the docs for v0.3 release.

**Comment by hcferguson** [comment]
As long as the installation instructions there are still valid, we are good to go.

**Comment by SaOgaz** [comment]
We will need to update the glue channel with the new release, but other then that I just tried the install instructions and they worked fine. Closing issue.
