### ISSUE TITLE
Update image viewers to newest version 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/mosviz#205]
Post V0.3 work:
The cutout viewer and 2d spectra viewer are both instances of glue's `StandaloneImageViewer`. We should update these to `glue.viewers.image.qt.data_viewer.ImageViewer`?

cc @astrofrog @hcferguson @kassin

**Comment by robelgeda** [comment]
This would allow region selection and other glue related functions. We can link regions on the 2d spectrum to regions in the SpecViz viewer. We can also attempt to link horizontal regions in the 2d viewer to regions in the cutout viewer (this might be a stretch since there is curvature in the dispersion). The key question is how much work is needed in the MOSViz viewer to account for this change (Image viewer function calls etc...)?

**Comment by kassin** [comment]
This is excellent potential new functionality but needs to be prioritized by the Product Owner (me) when looking at all the other issues.

I agree- the key question is how much effort this would require.  Even an estimate would be nice: 1 person for 1 week, 1 person for 1 month, etc.

**Comment by SaOgaz** [comment]
@nmearl, related to the drop down / not being able to open new specviz viewer?
