### ISSUE TITLE
Multiple Level 2 Products and Their Slits

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/mosviz#213]
Related to #175
A single `level3` product is a combination of multiple `level2` spectra files. This adds complications:

1. **Multiple files:** Since the MOSViz Table is source based (i.e each row is unique to a source) we would have to list all associated files in the same row. As of now, the table only has one column for `level2` products limiting it to a single `level2` file.

2.  **Multiple slits:** The `level2` products are spectra taken at different times, instrument positions and/or through different slits. This means that the "slit" in the `level3` data is actually a product of multiple silts. One suggestion that James Muzerolle had was to display all the `level2` slits in the cutout window when displaying `level3` 2d spectra. There are two challenges to consider:
     1. When displaying a `level3` 2D spectra, since there are are multiple slits, what should orientation of the cutout be to achieve slit-2D_Spectra alignment.
     2. If we do not use on the fly cutouts, we would have to generate multiple cutouts oriented correctly for each file or use retroject to orient each cutout.

3. **Slit Shapes:** Another point mentioned by James Muzerolle was that the slits in any of the s2d files is going to be distorted on the detector thus the alignment b/w the cutout and the s2d image is not exact.

CC: @hcferguson @kassin @brechmos-stsci @drdavella @SaOgaz

**Comment by robelgeda** [comment]
I think the first point is the most significant one and I believe we should rethink how we store file associations, slit geometries etc... 
An easy "fix" to this problem would be to stuff these file names into the meta of the ECSV file instead of making `level2` a column. A more long term solution would to use yaml or json type files, especially considering spectra with multiple MSA slits open during a single observation (i.e not the same as above) will require us to store complex slit geometries.

**Comment by robelgeda** [comment]
As for the slit alignment problem, I think the axes are aligned by default since they measure the same dimension in space. The only thing we would have to do is to rotate the cutout display projection to match the orientation of the 2D spectrum viewer projection. That way we can use a single cutout for each source and lose dependance on the WCS of the cutout. Furthermore this would remove the re-object dependency introduced by the Cutout Tool. 

 I think this can be work added to the #204 ticket.

**Comment by robelgeda** [comment]
Removed the `Urgent` tag because I don't think we can get this resolved by v0.3 releasee. @hcferguson @kassin @SaOgaz

**Comment by hcferguson** [comment]
@robel I agree that we cannot get this resolved by the v0.3 release. I do like the idea of stuffing the level 2 associations into the meta of the level 3 table, though. Not as required metadata, but optional if you are going to make use of level 2. That would allow us to make separate tables for the level 2 data, one per level 2 product (usually a different dither or different MSA configuration), and thus would keep the tables looking the same in the sense of having one spectrum and one slit per source.
