### ISSUE TITLE
[Reminder] SetupTools Requirement in readthedocs.yml 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/mosviz#223]
This ticket is a reminder to remove the following dependency in `readthedocs.yml`:

``requirements: setuptools==40.8.0 ``

#### Background:
There is a bug related to [read the docs and setuptools](https://github.com/rtfd/readthedocs.org/issues/5436). This should be fixed by a patch at #222. We need to remove the strict dependency once the bug has been addressed on the read the docs side of things.

**Comment by robelgeda** [comment]
Removing tags since this is not an active thread

**Comment by SaOgaz** [comment]
Turns out in addition to that, I had to add a setuptools and pip dependency in the environment.yml. So we should eventually remove those as well.
