### ISSUE TITLE
lupton_rgb.makeRGB() arguments

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/mosviz#23]
Playing with the lupton_rgb function and trying to match what I was able to do with the old [img_scale](https://github.com/marcelhaas/python/blob/master/img_scale.py) routine, I'm finding that the arguments to makeRGB may be too limiting (or at least to confusing for me on first attempt).

To get a decent looking color image usually involves some trial and error, but generally I find that
I want to set the floor a bit below the typical sky level and I want to set the ceiling close to the maximum pixel value (but this latter setting takes some fiddling). I almost always need to set these floors and ceilings *independently* for the different r,g,b images. I see that `minimum` can be a list, but it looks like `dataRange` is a float, implying it has to be the same for each band. I don't see a way to set the ceiling separately for each band.

Several separate suggestions here...feel free to split into separate issues if you like:

1. Rewrite the function so that it uses minimum and maximum, both possibly as lists. Get rid of dataRange, which is confusing. The documentation for `maximum` can then exactly parallel that for `minimum` which I think makes usage much clearer.

1. Write a separate helper function that will estimate sky levels and reasonable maximum values from the histogram of pixel values in the three separate input images. This helper function could be called from makeRGB or could call makeRGB to make the final image.  The following works okay for one test, but I think probably isn't general enough:
```
 for b in ['r','g','b']:
    mean, median, stddev = astats.sigma_clipped_stats(noisyimages[b],sigma=3.,iters=20)
    imin = median-2.*stddev
    imax = np.percentile(noisyimages[b],99.9)
```
In particular, when the brightest object in all the bands is red, it will come out white (because it is the brightest in all the bands). So I think to get good color scaling we have to provide a bit more control and I haven't found a good way to automate that (and I'm not sure it's a great idea to automate it for each individual cutout anyway).

**Comment by hcferguson** [comment]
Here is a somewhat kludgy way to allow the user to set the max and min levels *and* color of the brightest pixels. This uses ing_scale.asinh rather than the lupton_rgb version. 

```
# RGB image with flexible scaling of color of the brightest pixels
def makeRGB(rimg,gimg,bimg,minsigma=1.,maxpercentile=99.9,color_scaling=None,sigmaclip=3,iters=20,nonlinear=8.):
    ''' minsigma -- black level is set this many clipped-sigma below sky
       maxpercentile -- white level is set at this percentile of the pixel levels
       color_scaling -- list or array: maximum value is divided by this; 
                        so if you want the brightest pixels to be reddish, try, say 1.0,0.2, 0.1
       sigmaclip -- clipping threshold for iterative sky determination
       iters -- number of iterations for iterative sky determination
    '''
    bands = ['r','g','b']
    # Color scaling
    if color_scaling == None:
        cfactor = {'r':1.,'g':1.0,'b':1.0}
    else:
        cfactor = {}
        for i,b in enumerate(bands):
            cfactor[b] = color_scaling[i]
    images = {'r':rimg, 'g':gimg, 'b':bimg}
    rescaled_img = {}
    for b in ['r','g','b']:
        mean, median, stddev = astats.sigma_clipped_stats(images[b],sigma=sigmaclip,iters=iters)
        imin = median-minsigma*stddev
        imax = np.percentile(images[b],maxpercentile)
        rescaled_img[b] = img_scale.asinh(images[b],scale_min=imin,scale_max=imax/cfactor[b],non_linear=nonlinear)
        print imin,imax
    rgbimg = np.zeros((rescaled_img['r'].shape[0],rescaled_img['r'].shape[1],3),dtype=np.float64)
    rgbimg[:,:,0]=rescaled_img['r']
    rgbimg[:,:,1]=rescaled_img['g']
    rgbimg[:,:,2]=rescaled_img['b']
    return rgbimg
```

**Comment by pllim** [comment]
Moved to spacetelescope/astroimtools#33
