### ISSUE TITLE
Problem with testing the last release in Python 3.9

### ISSUE THREAD

**Issue by pllim** [spacetelescope/mosviz#234]
`pip install mosviz` downgrades `specviz` from 0.7.1 back to 0.7.0. Forcing `pip install specviz -U` after that emits this message: `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. mosviz 0.3.1 requires pyqt5==5.12.3, but you have pyqt5 5.8 which is incompatible.`

Same PySide traceback as spacetelescope/cubeviz#598

**Comment by pllim** [comment]
In a clean env with just mosviz, things seem to work (i.e., splash screen shows).

```
$ conda create -n <envname> python=3.9 qt
$ pip install mosviz
```

**Comment by pllim** [comment]
In Python 3.6, downgrade of `specviz` also did not happen. The splash screen shows.

**Comment by pllim** [comment]
(Ops... I misread the log. Downgrade still happens in Python 3.6. Updated my note above.)

**Comment by pllim** [comment]
Also works in Python 3.6, though the downgrade still happens.

**Comment by ibusko** [comment]
The original JIRA ticket is JDAT-1296.

**Comment by eteq** [comment]
In some out-of-band discussion, I think we settled on the following solution:

* Set the  maximum python version to whatever we know works right now (which I think is 3.6?)
* This has the downside that anyone who pip installs will get a downgrade
* ASAP, we put out a last version that has *none* of the current dependencies (and therefore leads to no downgrades), but just creates the error on import that says "go to jdaviz"
