### ISSUE TITLE
Add icons to toolbars

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/mosviz#37]
Currently, the MOSVizViewer doesn't contain icons, just labels. Add some icons for the sake of user usability.

**Comment by astrofrog** [comment]
Looks like this is done:

<img width="806" alt="screen shot 2018-06-14 at 10 16 14" src="https://user-images.githubusercontent.com/314716/41403129-06d55e14-6fbc-11e8-8068-32054f2fd273.png">
