### ISSUE TITLE
Populate info box with table info

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/mosviz#38]
It's desired to show the basic information from the table within the MOSViz viewer info area.

**Comment by astrofrog** [comment]
Looks like this is done (lower left):

<img width="806" alt="screen shot 2018-06-14 at 10 16 14" src="https://user-images.githubusercontent.com/314716/41403158-1ce9b498-6fbc-11e8-83b1-e2d7d50b22ca.png">
