### ISSUE TITLE
Fix slit placement on 2d image

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/mosviz#42]
Currently, the implementation is off. Needs tweaking.

**Comment by astrofrog** [comment]
We should not assume the slit is at the center of the cutout, so I think we should have something like slit_ra and slit_dec to give the position of the center of the slit. If we do this, we should also make it clear whether we expect the RA/Dec to be in a certain frame (e.g. FK5 J2000) or whether this is customizable.

**Comment by astrofrog** [comment]
This was implemented since this issue was opened and the slit is now shown at a specific ra/dec based on columns in the table:

<img width="806" alt="screen shot 2018-06-14 at 10 16 14" src="https://user-images.githubusercontent.com/314716/41403158-1ce9b498-6fbc-11e8-83b1-e2d7d50b22ca.png">
