### ISSUE TITLE
Show subsets in MOSViz Viewer layer widget

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/mosviz#43]
The layer widget remains empty even when a subset is selected. To be consistent with other viewers, it should show the current subset.

**Comment by javerbukh** [comment]
@astrofrog can you take a look at this in the next day or two?

**Comment by astrofrog** [comment]
Sorry for the delay, I'll try and look at this shortly

**Comment by astrofrog** [comment]
@nmearl - could you provide some screenshots to illustrate the issue? Locally if I make a subset then I can select it from the dropdown menu:

<img width="308" alt="screen shot 2018-10-15 at 14 42 25" src="https://user-images.githubusercontent.com/314716/46954461-917fc680-d088-11e8-9d58-bbbc7dafb2c4.png">

Do you mean that you want the 'active subset' dropdown menu to match the dropdown menu in the layer widget?

**Comment by astrofrog** [comment]
I think this was fixed in the mean time, so closing.
