### ISSUE TITLE
tests for data loaders

### ISSUE THREAD

**Issue by justincely** [spacetelescope/mosviz#45]
The data loaders need some unit tests.   Something simple enough may be to create datasets of the configuration we assume will work, call the function to make sure nothing breaks, cleanup the created files.

**Comment by robelgeda** [comment]
Tests are already have been added. Outdated ticket, closing.
[Data Loader Tests](https://github.com/spacetelescope/mosviz/blob/master/mosviz/loaders/tests/test_mos_loaders.py)
