### ISSUE TITLE
Add coveralls coverage testing

### ISSUE THREAD

**Issue by justincely** [spacetelescope/mosviz#46]

**Comment by pllim** [comment]
Note: Coverall check is meaningless until we have enough tests that cover stuff...

**Comment by astrofrog** [comment]
I think we have enough tests that this would be instructive (i.e. I'd like to know if it's 20% or 50%)

**Comment by javerbukh** [comment]
Run the coverall at the start of the sprint and again at the end so we can see how it improved.

**Comment by astrofrog** [comment]
I suggest we set up codecov - it's easy to do and we could just have it running in each PR.

**Comment by astrofrog** [comment]
(I'm happy to help if needed)

**Comment by brechmos-stsci** [comment]
Closed by https://github.com/spacetelescope/mosviz/pull/129
