### ISSUE TITLE
Initial numbered release

### ISSUE THREAD

**Issue by justincely** [spacetelescope/mosviz#52]
We need to put out a numbered release by COB so that i can include it in the recipe for AstroConda to build from.  

Since astroconda can specify minimum numbers, I'd like us to just bundle a release of 0.0.1, which i'll set as mosviz >= 0.0.1 in the metapackage.  In the event we need to do an increment before/during the workshop day, we can just bundle a new release and astroconda will allow people to update easily.

@nmearl you want to do this?  I'd be happy to bundle the release instead if you're busy, just need to know when you're happy with the current code base for me to dump as a 0.0.1

(anyone: also let me know if you see something wrong with the plan)

**Comment by nmearl** [comment]
@justincely It doesn't matter, really. We can make a tag and "cheat" the system by changing the revision that the tag points to. This avoids having to put in an astroconda PR for every change to the release.

I suggest we just make a 0.0.1rc1 pre-release tag now (I'm apprehensive about calling it a full release), and just submit the astroconda PR now.

It'd be great if you could take care of that, I've got my hands full with (spit) polishing as much as a I can with what little time I have right now. 😅

**Comment by justincely** [comment]
No problem, i'll take care of the release later this afternoon.  

For the release version - IMHO I think that a v0.0.x is an effective way to communicate an in-development codebase.  Adding the rcN at the end just seems to make it more complicated to version - then people have to remember both the code version and the release candidate version, and people are already confused about symantic versioning as it is.

Not a big deal either way, and i'm fine to do whichever you prefer, but throwing my vote in there for the simpler 0.0.1.  Let me know if my incredibly moving speech convinced you, or if you're going to remain horribly intransigent.  😈

**Comment by nmearl** [comment]
Hahah, all good points, and I always much prefer simplistic numbering schemes. This was a previous decision for SpecViz with the whole "onion skin" release cycle that's been brought up previously. Basically, a "release" didn't happen until it was publicized, hence the use of release candidates, and the pre-release git flag.

But, MOSViz is quite a different beast as it's not a stand-alone application. So, I think I can be convinced to eschew the nominal rigamarole for this by-the-set-of-our-pants YOLO release style you're proposing. 🌝

**Comment by justincely** [comment]
YOLO!
