### ISSUE TITLE
Cannot install via Astroconda

### ISSUE THREAD

**Issue by kassin** [spacetelescope/mosviz#64]

**Comment by astrofrog** [comment]
I can also add the developer version of mosviz to the ``glueviz`` channel

**Comment by astrofrog** [comment]
It's now possible to install MOSViz using:

```
conda create -c glueviz/label/dev -n test-mosviz mosviz python=3.6
```

That is, there is a ``mosviz`` channel in the ``glueviz/label/dev`` channel. Once we have a stable release, there will be a conda package in the ``glueviz`` channel.

**Comment by brechmos-stsci** [comment]
@astrofrog We talked about this yesterday a bit. We are going to plan on doing a release later next week. So, if you could confirm the mechanisms via glueviz conda are good.  

I'll create a separate ticket for the actual release early next week.

**Comment by astrofrog** [comment]
@brechmos-stsci - the glueviz channel should work fine but I'll need to be told when the release is done to make sure the build is triggered. However, one issue I foresee is that if we are dependent on the new specviz, we'll need to do a release of specviz first? Or are we still relying on the old specviz for now?

**Comment by brechmos-stsci** [comment]
Yes, this will use the new specviz.  The plan is mid next week to start all this stuff. I am going to create a ticket in mosviz for the release.

**Comment by brechmos-stsci** [comment]
Closing as this will be worked out next week with the new release.
