### ISSUE TITLE
Error when loading  a bad data set or when loading an incorrect file type

### ISSUE THREAD

**Issue by kassin** [spacetelescope/mosviz#69]
Instead of showing a small red symbol in the lower right, add in something like a pop up error message.

**Comment by javerbukh** [comment]
Solved by the QDialog that pops up when loading files into mosviz. The test I used was to try loading the manga data cube into mosviz and I received multiple error boxes as well as the main DataLoader QDialog, which asks for the user to provide data corrections in order to proceed.
