### ISSUE TITLE
Check if WCS is available 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/mosviz#78]
Some headers do not contain WCS info. A check is necessary in `MOSVizViewer.render_data` to handle this issue. The following is an example of an error:
Line: `wcs = spec2d_data.coords.wcs`
Error: `AttributeError: 'Coordinates' object has no attribute 'wcs'`

**Comment by javerbukh** [comment]
Solved with PR #112

**Comment by hcferguson** [comment]
I don't see an indication on the PR that was retested, but I perhaps I missed it. Once it's been tested on a file without a WCS in the header, I think this issue can be closed.

**Comment by robelgeda** [comment]
Outdated

**Comment by SaOgaz** [comment]
Outed, we've opened a new (sort of related) issue: #203
