### ISSUE TITLE
Use glue 'fixed layout' functionality?

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/mosviz#86]
We could consider using a fixed layout for MOSViz as we did for cubeviz.

**Comment by astrofrog** [comment]
That's true - maybe it's fine as-is then.

**Comment by kassin** [comment]
I agree with @nmearl that MOSVis should not have a fixed layout.  Our eventual goal for CubeViz is to "free the windows" so that the layout can be changed by the user.
