### ISSUE TITLE
Add appveyor to Github test infrastructure

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/mosviz#90]
I believe only travis is working for mosviz, so we will need to add Appveyor for the Windows testing.

**Comment by astrofrog** [comment]
I add add the config file but I think someone else might have to actually enable the project on appveyor.com.

**Comment by brechmos-stsci** [comment]
I believe I now added it to appveyor on their site. I'll confirm shortly.

**Comment by astrofrog** [comment]
Thanks, I'm fixing the AppVeyor config in https://github.com/spacetelescope/mosviz/pull/98
