### ISSUE TITLE
Setup qtbot for UI testing

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/mosviz#92]
There do not appear to be any (substantial) tests, so one initial step will be to setup some basic tests using the qtbot (could be replicated from cubeviz).

**Comment by javerbukh** [comment]
@brechmos-stsci should I start writing the tests in [test_mos_viewer.py](https://github.com/spacetelescope/mosviz/blob/master/mosviz/viewers/tests/test_mos_viewer.py) or somewhere else?

**Comment by brechmos-stsci** [comment]
Sure, go for it.  We might move the file later, but if it works there for now, it is more important to get going on writing tests :)....

Thanks.

**Comment by javerbukh** [comment]
The requirements for this issue have been met, a new issue will be opened for Sprints 2+ to continue to add Mosviz testing.
