### ISSUE TITLE
Pipeline steps, output formats related to Mosviz

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/mosviz#94]
We need to look into the current pipeline steps and output formats. 
* What is saved at which step? 
* What format is the data in?
* Does Mosviz have the ability to read in these intermediate steps?
* What type of work will need to happen to read in the intermediate steps?

**Comment by kassin** [comment]
@mfixstsci Are you ok looking into this?  Let's talk.

**Comment by javerbukh** [comment]
Get pipeline formats from the instrument teams. If that doesn't work, Susan will talk to the developers. James Muzerolle, Brian Hilbert, and Alicia Canipe are points of contact from the Instrument teams. Phil Hodge and James Davies are points of contact from the developers side.

**Comment by kassin** [comment]
NIRSpec team:  Only level 2 data are available.  And only a few spectra are available.  The pipeline takes many many hours to run for a single spectrum, and my team lead couldn't even get it to finish.  Level 3 (combined exposures) are not yet ready.  The pipeline has not yet reached level 3 products for the NIRSpec MSA.

@brechmos-stsci Can you possibly ask someone on the development end?  I'd be fine if they could "fake" up a level 3 product.  Previously, Jonathan Eisenhamer did this for us.  Let me know if you run into a dead-end.

**Comment by kassin** [comment]
Spectra are at: /astro/3/jwst_da_sprint_testdata/mostools/NIRSpec_simulated_July2018
From the README file:
data from James Muzerolle.

This is a level 2 simulated MSA observation of one object.  It has been run through the NIRSpec pipeline.  The pipeline has not yet reached level 3.

This is *one* of three nodded exposures.

**Comment by kassin** [comment]
@brechmos-stsci I think the data I posted above is the level 2B data you are referring to?

**Comment by hcferguson** [comment]
Some info on formats from Phil Hodge. 

Here is a link to our documentation:

     https://jwst-pipeline.readthedocs.io/en/latest/

In that page, clicking on "Available Pipelines" gives you info on running the steps and pipelines, and this page:

https://jwst-pipeline.readthedocs.io/en/latest/jwst/package_index.html

gives info on the individual steps and pipelines.  I have to admit, the description for extract_1d is not as detailed as I thought.

I copied three files to /user/hodge/temp/examples/ .  The files with these suffixes would normally be created one after another, but I use these particular files for testing, and they're not strictly sequential.  For example, the ASDF extension in the assign_wcs.fits file might not be up to date, and this file should contain a number of other extensions, as seen in nrs1_SloperPipeline_extract_2d.fits.

nrs1_SloperPipeline_assign_wcs.fits is the output of assign_wcs and the input to extract_2d.  This is a 2-D image covering the whole NIRSpec detector (NRS1).

nrs1_SloperPipeline_extract_2d.fits is the output of extract_2d and the input to extract_1d.  This has five SCI extensions, one for each 2-D cutout, and each has (in this case) a different size.  It includes a number of other extensions for each cutout, e.g. an array of wavelengths (same size as the SCI extension), variance estimates (VAR_POISSON and VAR_RNOISE).

nrs1_SloperPipeline_extract_1d.fits is the output of extract_1d. Here is a list of its contents (like the output of the catfits task):

HDU#  FILENAME             EXTNAME    EXTVER DIMENS         BITPIX
0     nrs1_SloperPipeline_extract_1d.fits                   8
1       BINTABLE           EXTRACT1D  1      8Fx1920R       8
2       BINTABLE           EXTRACT1D  2      8Fx1728R       8
3       BINTABLE           EXTRACT1D  3      8Fx1847R       8
4       BINTABLE           EXTRACT1D  4      8Fx1140R       8
5       BINTABLE           EXTRACT1D  5      8Fx1020R       8
6       BINTABLE           ASDF              1Fx110118R     8

Each EXTRACT1D extension is a BINTABLE with the following columns:

--> tlcol nrs1_SloperPipeline_extract_1d.fits[1]
# nrs1_SloperPipeline_extract_1d.fits[1]
WAVELENGTH       D         %25.16g um
FLUX             D         %25.16g mJy
ERROR            D         %25.16g mJy
DQ               I            %11d ""
NET              D         %25.16g DN/s
NERROR           D         %25.16g DN/s
BACKGROUND       D         %25.16g DN/s
BERROR           D         %25.16g DN/s

Here is part of the header for one of those tables:

SLTNAME = 'S200A1  '           / Name of the slit
SLITID  =                    0 / Slitlet ID
SOURCEID=                    0 / Source ID
SRCXPOS =                  0.0 / Source position in slit (x-axis)
SRCYPOS =                  0.0 / Source position in slit (y-axis)
SHUTSTA = '' / All (open and close) shutters in a slit
SLIT_RA =    5.300868647496155 / Right ascension (deg) at middle of slit
SLIT_DEC=   -72.13294256809922 / Declination (deg) at middle of slit
SPORDER =                   -1 / Spectral order number

**Comment by brechmos-stsci** [comment]
@hcferguson Data loading and load-ability will be an ongoing thing.  Is this ticket at the stage where we can close it (for the previous milestone)?

**Comment by hcferguson** [comment]
@brechmos-stsci It should not hold up the release, if that's what you are asking. I'd be inclined to leave it open and remove the sprint3 milestone, but if you'd prefer to close it and immediately open others that's okay. These could be multiple issues or all on one issue:

- Read level 3 NIRSpec data
- Create the target table for NIRSpec level 3 data if not present
- Read level 2 NIRSpec data
- Create the target table for NIRSpec level 2 data if not present (or add pointers to the level 2 data to the level 3 table if that's present)

**Comment by javerbukh** [comment]
Make sure we can handle level 2 and level 3 in #157
