### ISSUE TITLE
Organize and document example datasets

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/mosviz#97]
We will need to organize and document example datasets for testing of mosviz (and note which are public datasets or private ones).

**Comment by kassin** [comment]
Please assign to me too.

**Comment by kassin** [comment]
Demo data from a workshop: /astro/3/jwst_da_sprint_testdata/mostools/workshop_examples
See README file in this directory.

**Comment by kassin** [comment]
Various test data sets are in: /astro/3/jwst_da_sprint_testdata/mostools
They are not all formatted for MOSViz.

Galaxies from redshifts ranging from 0.2 to 1.2 with Hubble images:
z1Galaxies_Kassin
z1Galaxies_Kassin_JDE (the above edited by Eisenhammer - not sure what he did)

Planetary nebula observations:
PN_Muzerolle

nircam_nirspec_catalog: not sure what this is, perhaps an attempt to wrap the data below

Various simulated NIRSpec spectra (these are out of date):
SimulatedData* directories
nirspec_msa_simulated_3nod 
NIRSpec_engineering_DeOliveira

Various simulated NIRCam images (these are likely out of date):
NIRCam_simulated* directories

**Comment by brechmos-stsci** [comment]
>  They are not all formatted for MOSViz.

Are they all in some common format so that we could write a short script to convert from the "not formatted for MOSViz" to be formatted for MOSViz?  Or is the data not in a standard format currently?

**Comment by javerbukh** [comment]
This information is to be put on a confluence page and then this ticket will be closed. @brechmos-stsci

**Comment by brechmos-stsci** [comment]
I created a page at https://innerspace.stsci.edu/display/DATB/MosViz that organizes the list of data for internal use.  Discussion about specific data should move to that page.
